## service definition
version:"3.3"
services:
  webserver:
    image:ubuntu
    ports:
      - "80:80"
    networks:
      - webnet

  redis:
    image:redis
    networks:
      - webnet

## Network definition
networks:
  webnet:

## Data volume definition
Volumes:
  data-volume: